# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newshome', '0002_auto_20161014_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marquee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marquee_text', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='article_views',
            field=models.IntegerField(default=0),
        ),
    ]
