# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 07:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newshome', '0006_auto_20161016_1324'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PollC',
            new_name='PollChoice',
        ),
        migrations.RenameModel(
            old_name='PollQ',
            new_name='PollQuestion',
        ),
    ]
