# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 19:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newshome', '0007_auto_20161016_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_views',
        ),
    ]
