# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newshome', '0010_auto_20161018_0059'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateHead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
            ],
        ),
    ]
