# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 20:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newshome', '0011_datehead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datehead',
            name='date',
        ),
    ]
