# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('TECH', 'Technology'), ('OASIS', 'Oasis'), ('DEP', 'Departments'), ('CLUB', 'Clubs'), ('ACADS', 'Academics')], default='CLUB', max_length=10)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Article')),
            ],
        ),
    ]
