# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('TECH', 'Technology'), ('OASIS', 'Oasis'), ('DEP', 'Departments'), ('CLUB', 'Clubs'), ('ACADS', 'Academics')], max_length=10),
        ),
    ]
